CREATE TABLE EMPRESA(
    ID_EMPRESA VARCHAR(20),
    LOCALIZACION VARCHAR(100),
    CONSTRAINT PK_ID_EMPRESA PRIMARY KEY (ID_EMPRESA)
);
CREATE TABLE CLIENTE(
    ID_CLIENTE VARCHAR(20),
    NOMBRE VARCHAR(100),
    SALDO INTEGER(20),
    DESCUENTO INTEGER(20),
    CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);
CREATE TABLE ARTICULO(
    ID_ARTICULO VARCHAR(20),
    TIPO VARCHAR(100),
    CANTIDAD INTEGER(20),
    ID_EMPRESA VARCHAR(20),
    CONSTRAINT PK_ID_ARTICULO PRIMARY KEY (ID_ARTICULO),
    CONSTRAINT FK_ID_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);
CREATE TABLE PEDIDO(
    ID_PEDIDO VARCHAR(20),
    FECHA DATE,
    DIRECCION VARCHAR(100),
    ID_CLIENTE VARCHAR(20),
    ID_ARTICULO VARCHAR(20),
    CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_ID_ARTICULO FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO)
);
